default: &default
  adapter: postgresql
  encoding: unicode
  #host: db
  host: localhost
  port: 5432
  username: postgres
  #password: <%= ENV['POSTGRES_PASSWORD'] %>
  #<<: *default
  #database: new-leaders-api2_development
  

development:
  <<: *default
  database: psp_development

test:
  <<: *default
  database: psp_test

production:
  <<: *default
  database: psp_production
  username: root
  password: dfkjer5fdwaf!
  pool: 5
  host: new-leaders.czps0byobfz2.us-east-2.rds.amazonaws.com
  port: 5432
